version: '3.6'

services:
#  api:
#    image: 'nada-hassan-platform'
#    container_name: platform
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresdb
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/platform
#      - SPRING_DATASOURCE_USERNAME=platform
#      - SPRING_DATASOURCE_PASSWORD=platform
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=platform
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=platform