management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: ["health","info","metric","cacheManagement"]

spring:
  jackson:
    default-property-inclusion: NON_NULL
  flyway:
    baselineOnMigrate: true
    table: flyway_application_schema_history
  profiles:
    active: local
  application:
    name: nada-hassan-platform
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      maximum-pool-size: 2
    url: jdbc:postgresql://localhost:5432/platform
    username: platform
    password: platform
  config:
    activate:
      on-profile: local

---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    url: jdbc:postgresql://postgresdb:5432/platform
    username: platform
    password: platform
  config:
    activate:
      on-profile: docker

 #Production database configuration
---
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      javax:
#        persistence:
#          validation:
#            mode: none
#  datasource:
#    url: ${RDS_URL}
#    username: workmotion
#    password: ${RDS_PASSWORD}
#  config:
#    activate:
#      on-profile: prod


---
spring:
  cache:
    cache-names: products-cache
    caffeine:
      spec: maximumSize=500